### ISSUE TITLE
Error "DriveAlreadyExists" when Site code = "ENV"

### ISSUE THREAD

**Issue by Daren9m** [paulwetter/DocumentConfigMgrCB#46] opened 2019-09-12 20:43 UTC
I posted this on your blog as well, but it appears people are actively using the issues feature here on github.

Our site code is "ENV" and I think that is causing syntax issues. I used the -verbose switch and here are the details surrounding the errors I get. Any help is greatly appreciated!

PS C:\Temp\DocumentConfigMgrCB-master> .\DocumentCMCB.ps1 -CompanyName "MyCompany" -CompanyLogo "C:\temp\Logo.jpg" -Author "ME" -AddDateTime -verbose
Beginning Execution of version 3.42 at: 9:57 AM

[break]

VERBOSE: Loading 'FormatsToProcess' from path 'E:\Program Files\Microsoft Configuration
Manager\AdminConsole\bin\Microsoft.ConfigurationManagement.PowerShell.Provider.format.ps1xml'.
Import-Module : A drive with the name 'ENV' already exists.
At C:\Temp\DocumentConfigMgrCB-master\DocumentCMCB.ps1:1215 char:3
+ Import-Module ($env:SMS_ADMIN_UI_PATH.Substring(0,$env:SMS_ADMIN_UI_PATH.Lengt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ResourceExists: (ENV:String) [Import-Module], ProviderInvocationException
+ FullyQualifiedErrorId : DriveAlreadyExists,Microsoft.PowerShell.Commands.ImportModuleCommand

VERBOSE: Exporting function 'Add-CMDeviceCollectionExcludeMembershipRule'.
VERBOSE: Exporting function 'Add-CMDeviceCollectionIncludeMembershipRule'.

[break]

VERBOSE: Importing function 'Remove-CMUserCollectionQueryMembershipRule'.
VERBOSE: 09/12/2019 09:57:59: Getting Site Information
Get-CMSite : This command cannot be run from the current drive. To run this command you must first connect to a
Configuration Manager drive.
At C:\Temp\DocumentConfigMgrCB-master\DocumentCMCB.ps1:1232 char:12
+ $CMSites = Get-CMSite
+ ~~~~~~~~~~
+ CategoryInfo : DeviceError: (Microsoft.Confi....GetSiteCommand:GetSiteCommand) [Get-CMSite], InvalidOpe
rationException
+ FullyQualifiedErrorId : CommandCannotExecuteFromCurrentDrive,Microsoft.ConfigurationManagement.Cmdlets.HS.Comman
ds.GetSiteCommand

VERBOSE: 09/12/2019 09:58:00: Completed Checking each site's configuration.
VERBOSE: 09/12/2019 09:58:00: Enumerating all Site Boundaries
Get-CMBoundary : This command cannot be run from the current drive. To run this command you must first connect to a
Configuration Manager drive.
At C:\Temp\DocumentConfigMgrCB-master\DocumentCMCB.ps1:2516 char:15
+ $Boundaries = Get-CMBoundary
+ ~~~~~~~~~~~~~~
+ CategoryInfo : DeviceError: (Microsoft.Confi...BoundaryCommand:GetBoundaryCommand) [Get-CMBoundary], In
validOperationException
+ FullyQualifiedErrorId : CommandCannotExecuteFromCurrentDrive,Microsoft.ConfigurationManagement.Cmdlets.HS.Comman
ds.GetBoundaryCommand

[end]

**Comment by paulwetter** [comment] 2019-09-13 12:44
Yah, the blog doesn't email new comments to me.  Can you use any of the PowerShell Cmdlets for ConfigMgr?  Probably not because you cannot change to the **ENV:** site code drive because $ENV is already used by PowerShell for Environmental variables (%AppData%, %ProgramFiles%, etc)  So, I cannot reproduce and test but, you can try the following and should logically work.  however, no idea on dependencies for the environmental variables.

That said, the following is the best chance i can logically think of:

Start PowerShell.  Run the following command:
`get-psdrive` 
You'll should see **Env** listed with *Provider* of *Environment*.
Now, type the following to remove it.
`Remove-PSDrive Env`
Now, load the powershell module for SCCM, because that depends on $Env in 
`import-module "C:\Program Files\Microsoft Configuration Manager\AdminConsole\bin\ConfigurationManager.psd1"`
     Path may vary for your system.
Then test a cmdlet.
`CD ENV:`
`Get-CMSite`
This should return something.
If it does, `CD C:`.
Then try running the script per usual instructions.

**Comment by Daren9m** [comment] 2019-09-13 15:14
Thank you very much, Paul! We were trying to find a way to alias the ENV provider or the SCCM drive, but this makes a lot more sense. I will try this today.

**Comment by paulwetter** [comment] 2019-09-25 16:36
Closing this as something that will not be fixed.  ENV should be a restricted site code because of the PowerShell ENV provider.

**Closed by paulwetter** 2019-09-25 16:36 UTC
