### ISSUE TITLE
Incorrect Discovery Method Status reported

### ISSUE THREAD

**Issue by Skatterbrainz** [paulwetter/DocumentConfigMgrCB#57] opened 2020-03-06 21:44 UTC
The site discovery methods is showing "disabled" for all methods, even though all but network discovery are enabled.

**Comment by paulwetter** [comment] 2020-03-06 22:34
Hmmmmm.  I will take a look this weekend.  If probably have a decimal point in the wrong place somewhere. I always miss some mundane detail. 🙂

**Comment by paulwetter** [comment] 2020-03-07 06:28
Hmmm.... I am not seeing this at my end.... Server OS, CM build,  and PowerShell version you running against?

**Comment by ChadSimmons** [comment] 2020-03-27 23:29
I could not reproduce the issue.
Windows Server 2012 R2, CM 1906 (5.0.8853.100), PoSH 5.1.14409.1018

**Comment by Alpanama** [comment] 2020-06-19 11:10
This issue could be produced by running the script from a computer, not from the MECM/SCCM  server. Do you get the "Get-WmiObject : Invalid namespace "ROOT\SMS\site_XXX" error from the script? If so, try to run it from the server, mainly because the namespace "ROOT\SMS\..." does not exist on a computer but in the MECM/SCCM server.

**Comment by paulwetter** [comment] 2020-06-20 04:43
Thank you @Alpanama .  This helps a bunch.  I was missing the computername parameter on my WMI queries.  Should be fixed in the latest push tonight.  I has some other items in the build that I hope i had finished.  (was working on Phased Deployments).

So hopefully everything is working in 3.52 now (9d47bbca56907a55084b680b7ab0935e6e1e2ff4)

**Comment by paulwetter** [comment] 2020-07-24 06:04
So, closing.  Pretty sure this is fixed.

**Closed by paulwetter** 2020-07-24 06:04 UTC
Labels: bug
